language: php
matrix:
  fast_finish: true
  include:
  - php: 5.3
    env:
      EXECUTE_BUILD_DOCS=false
  - php: 5.4
    env:
      EXECUTE_BUILD_DOCS=false
  - php: 5.5
    env:
      EXECUTE_BUILD_DOCS=false
  - php: 5.6
    env:
      EXECUTE_BUILD_DOCS=true
  - php: 7.0
    env:
      EXECUTE_BUILD_DOCS=false
  - php: hhvm
    env:
      EXECUTE_BUILD_DOCS=false
  allow_failures:
  - php: 7.0
  - php: hhvm
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "testing-docs" && test $EXECUTE_BUILD_DOCS == "true" && bash deploy.sh
