language: php
matrix:
  fast_finish: true
  include:
  - php: 5.3
  - php: 5.4
  - php: 5.5
  - php: 5.6
    env:
      - DEPLOY_DOCS="$(if [[ $TRAVIS_BRANCH == 'testing-docs' && $TRAVIS_PULL_REQUEST == 'false' ]]; then echo -n 'true' ; else echo -n 'false' ; fi)"
  allow_failures:
  - php: 7.0
  - php: hhvm
after_success:
  - if [[ $DEPLOY_DOCS == "true" ]]; then echo "Preparing to build and deploy documentation" ; bash ./deploy.sh ; echo "Completed deploying documentation" ; fi
env:
  global:
    secure: axILogB/yRkXzqGDWL6JnuqmRE7irv12yXDo7KItyUlF/JciTqIjDH78iydw+KgcU57tWNiGwBSuQjF/+sjNEWt2jONiL5jT5eOIVso52xzyyFQFBxT8iqp8Bj5zqF18BLYY94fj36DjIV+//q7cFWAbKdVX81ZLcTtEcNMdpTaUd2eT8DASMNHzKcyU=g2w1oDnvvqf7Cjn+O4eH7tnA2gi5taaD6XrwQqSqZPZaZbE/SsYOgzHwMvPL1VxH++nN+m4YXXBbC3I3+rkOszhcS8pvd256IFABMG8eBN5XaFgOBy3Uq1e7yQU4gx3kOvbh5uXZ77X1OYVRUnQlKJcP4nAvvESew8g/ugdm98FqAPKZp0DnkfS40Dx6cBp4NlVlmXo4aBKncQWGLrQ4piUc5C6qbMwdjZOLmZAtZV0iq72hrSHtvfUAUUyo/VhhqKT92PzY9sHpdcxCwP8+QoNBZ1ll1jRdxEjt/pnQWvfqzsW9cnQ9Tz0m4astdker75ZsckKTAQuSBrDmges9rGD+uRl011Bnee4NjRalaCf85rqNUuVRC1BBylcwJt6HIetj5iP55h3xdNihC/jt5HwcVPmHkbftIVdMwZbl7qA0l4Q3O1buS+CnWLc89rGwGjBpnDXuENAPbqzzrxqQE6NZVn3VPOZq0aAuhmyaYCOA=
