language: php
matrix:
  fast_finish: true
  include:
  - php: 5.3
  - php: 5.4
  - php: 5.5
  - php: 5.6
  - php: 7.0
  - php: hhvm
  allow_failures:
  - php: 7.0
  - php: hhvm
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "testing-docs" && bash deploy.sh
