site_name: LibreNMS Documentation
theme: mkdocs
docs_dir: doc
site_dir: out
site_url: https://laf.github.io/docs
markdown_extensions:
    - pymdownx.superfences
extra_css:
    - librenms.css
google_analytics: false
include_next_prev: false
